### ISSUE TITLE
Uninstall / Remove Color Picker

### ISSUE THREAD

**Issue by Wiredframe** [zeplin/color-picker#6]
How to uninstall / remove color picker? I already uninstalled Zeplin on my Mac but the color picker is still present.

**Comment by kardeslik** [comment]
Hey @Wiredframe,
Sorry for the hassle!
You can remove it via following command
```
rm -rf ~/Library/ColorPickers/ZeplinColorPicker.colorPicker
```
or you can use Finder to go to `~/Library/ColorPickers` directory and delete `ZeplinColorPicker.colorPicker` within Finder.

**Comment by berkcebi** [comment]
Just added these instructions to the README @kardeslik, heads up. 👀 

Thanks @Wiredframe!
